import os
import numpy as np
import pandas as pd
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
import ta
import matplotlib.pyplot as plt

class DataLoader:
    def __init__(self, ticker="BTC-USD", start_date="2020-01-01", end_date=None):
        self.ticker = ticker
        self.start_date = start_date
        self.end_date = end_date
    
    def fetch_data(self):
        print(f"Fetching data for {self.ticker}...")
        df = yf.download(self.ticker, start=self.start_date, end=self.end_date)
        if df.empty:
            raise ValueError(f"No data found for {self.ticker}.")
        
        # Flatten multi-level columns if yfinance returns them
        if isinstance(df.columns, pd.MultiIndex):
            # For recent yfinance versions, columns are (Price, Ticker)
            df.columns = df.columns.droplevel(1)
            
        print(f"Data fetched: {df.shape[0]} rows.")
        return df

class FeatureEngineer:
    @staticmethod
    def add_technical_indicators(df):
        print("Adding technical indicators...")
        df = df.copy()
        
        # RSI
        df['RSI'] = ta.momentum.RSIIndicator(close=df['Close'], window=14).rsi()
        
        # MACD
        macd = ta.trend.MACD(close=df['Close'])
        df['MACD'] = macd.macd()
        df['MACD_Signal'] = macd.macd_signal()
        df['MACD_Diff'] = macd.macd_diff()
        
        # Bollinger Bands
        bollinger = ta.volatility.BollingerBands(close=df['Close'], window=20, window_dev=2)
        df['BB_High'] = bollinger.bollinger_hband()
        df['BB_Low'] = bollinger.bollinger_lband()
        df['BB_Mid'] = bollinger.bollinger_mavg()
        
        # Moving Averages
        df['SMA_20'] = ta.trend.SMAIndicator(close=df['Close'], window=20).sma_indicator()
        df['EMA_50'] = ta.trend.EMAIndicator(close=df['Close'], window=50).ema_indicator()
        
        # Lag features
        df['Close_Lag1'] = df['Close'].shift(1)
        
        return df

class PreProcessor:
    def __init__(self, sequence_length=60):
        self.sequence_length = sequence_length
        self.scaler = MinMaxScaler(feature_range=(0, 1))
        self.features = None
        self.target_idx = None
        
    def preprocess_train(self, df, target_col='Close'):
        print("Preprocessing data for training...")
        # Handle NA values generated by technical indicators
        df = df.dropna()
        
        self.features = df.columns.tolist()
        self.target_idx = self.features.index(target_col)
        
        # Normalize
        scaled_data = self.scaler.fit_transform(df)
        
        X, y = [], []
        for i in range(self.sequence_length, len(scaled_data)):
            X.append(scaled_data[i - self.sequence_length:i])
            y.append(scaled_data[i, self.target_idx])
            
        return np.array(X), np.array(y), df
        
    def preprocess_inference(self, df):
        # Used during deployment for next prediction
        df = df.dropna()
        scaled_data = self.scaler.transform(df)
        # We just need the last `sequence_length` items
        X = [scaled_data[-self.sequence_length:]]
        return np.array(X)

    def get_scaler(self):
        return self.scaler

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader as TorchDataLoader

class PyTorchLSTM(nn.Module):
    def __init__(self, input_size):
        super(PyTorchLSTM, self).__init__()
        self.lstm1 = nn.LSTM(input_size, 50, batch_first=True)
        self.dropout1 = nn.Dropout(0.2)
        self.lstm2 = nn.LSTM(50, 50, batch_first=True)
        self.dropout2 = nn.Dropout(0.2)
        self.fc1 = nn.Linear(50, 25)
        self.fc2 = nn.Linear(25, 1)

    def forward(self, x):
        out, _ = self.lstm1(x)
        out = self.dropout1(out)
        out, _ = self.lstm2(out)
        out = self.dropout2(out)
        out = out[:, -1, :]
        out = self.fc1(out)
        out = self.fc2(out)
        return out

class CryptoLSTM:
    def __init__(self, sequence_length=60, features_count=1):
        self.sequence_length = sequence_length
        self.features_count = features_count
        self.device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
        self.model = PyTorchLSTM(features_count).to(self.device)
        self.criterion = nn.MSELoss()
        self.optimizer = optim.Adam(self.model.parameters())
        
    def train(self, X_train, y_train, epochs=20, batch_size=32, validation_split=0.1):
        print("Training model using PyTorch...")
        val_size = int(len(X_train) * validation_split)
        train_size = len(X_train) - val_size
        
        X_t = torch.tensor(X_train[:train_size], dtype=torch.float32).to(self.device)
        y_t = torch.tensor(y_train[:train_size], dtype=torch.float32).view(-1, 1).to(self.device)
        
        X_val = torch.tensor(X_train[train_size:], dtype=torch.float32).to(self.device)
        y_val = torch.tensor(y_train[train_size:], dtype=torch.float32).view(-1, 1).to(self.device)
        
        dataset = TensorDataset(X_t, y_t)
        loader = TorchDataLoader(dataset, batch_size=batch_size, shuffle=True)
        
        best_val_loss = float('inf')
        patience_counter = 0
        patience = 5
        
        for epoch in range(epochs):
            self.model.train()
            train_loss = 0
            for batch_X, batch_y in loader:
                self.optimizer.zero_grad()
                outputs = self.model(batch_X)
                loss = self.criterion(outputs, batch_y)
                loss.backward()
                self.optimizer.step()
                train_loss += loss.item() * batch_X.size(0)
            train_loss /= len(loader.dataset)
            
            self.model.eval()
            with torch.no_grad():
                val_outputs = self.model(X_val)
                val_loss = self.criterion(val_outputs, y_val).item()
                
            print(f"Epoch {epoch+1}/{epochs} - loss: {train_loss:.4f} - val_loss: {val_loss:.4f}")
            
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                torch.save(self.model.state_dict(), 'best_model.pt')
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= patience:
                    print("Early stopping")
                    break
                    
        if os.path.exists('best_model.pt'):
            self.model.load_state_dict(torch.load('best_model.pt', map_location=self.device, weights_only=True))
            os.remove('best_model.pt')
        return None
        
    def predict(self, X):
        self.model.eval()
        with torch.no_grad():
            X_tensor = torch.tensor(X, dtype=torch.float32).to(self.device)
            preds = self.model(X_tensor)
        return preds.cpu().numpy()
        
    def save(self, filepath):
        torch.save(self.model.state_dict(), filepath)
        
    @classmethod
    def load(cls, filepath, sequence_length, features_count):
        instance = cls(sequence_length, features_count)
        instance.model.load_state_dict(torch.load(filepath, map_location=instance.device, weights_only=True))
        instance.model.eval()
        return instance

class Evaluator:
    @staticmethod
    def evaluate(y_true, y_pred, scaler, target_idx, features_count):
        from sklearn.metrics import mean_squared_error, mean_absolute_error
        
        # Inverse transform to get actual prices
        dummy_true = np.zeros((len(y_true), features_count))
        dummy_true[:, target_idx] = y_true
        y_true_inv = scaler.inverse_transform(dummy_true)[:, target_idx]
        
        dummy_pred = np.zeros((len(y_pred), features_count))
        dummy_pred[:, target_idx] = y_pred.flatten()
        y_pred_inv = scaler.inverse_transform(dummy_pred)[:, target_idx]
        
        rmse = np.sqrt(mean_squared_error(y_true_inv, y_pred_inv))
        mae = mean_absolute_error(y_true_inv, y_pred_inv)
        
        print(f"RMSE: {rmse:.2f}")
        print(f"MAE: {mae:.2f}")
        
        return y_true_inv, y_pred_inv, rmse, mae
        
    @staticmethod
    def plot_predictions(y_true_inv, y_pred_inv, dates, save_path=None):
        plt.figure(figsize=(14, 5))
        plt.plot(dates, y_true_inv, color='blue', label='Actual Crypto Price')
        plt.plot(dates, y_pred_inv, color='red', label='Predicted Crypto Price')
        plt.title('Cryptocurrency Price Prediction')
        plt.xlabel('Time')
        plt.ylabel('Price')
        plt.legend()
        plt.grid(True, alpha=0.3)
        if save_path:
            plt.savefig(save_path)
            print(f"Plot saved to {save_path}")
        else:
            plt.show()
